name: Continuous Integration and Delivery

on:
  push:
    branches: [ master ]

env:
  DJANGO_IMAGE: docker.io/koroses/django-helloword-argo

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Log in to Docker Hub
        run: echo ${PASSWORD} | docker login -u ${{ secrets.USENAME }} --password-stdin
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Build images
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t ${{ env.DJANGO_IMAGE }}:${GITHUB_REF##*/}-$git_hash .
      - name: Push images
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker push ${{ env.DJANGO_IMAGE }}:${GITHUB_REF##*/}-$git_hash
      - name: Update Version
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          version=$(cat ./kubernetes/django-deployment.yaml | grep image: | awk '{print $2}')
          sed -i "s#$version#${GITHUB_REF##*/}-$git_hash#" ./kubernetes/django-deployment.yaml
            
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          commit_message: Version updated